// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

/**
 * Central tuning constants for whole-robot behaviors that don't belong to a single generated file.
 *
 * <p>Hardware/drivetrain constants (device IDs, gear ratios, drive PID, {@code kSpeedAt12Volts})
 * are generated by Tuner X and live in {@link frc.robot.generated.TunerConstants} - do not
 * duplicate them here. This class holds the <i>physics</i> and <i>profiling</i> parameters that the
 * custom trajectory engine and the traction limiter need, isolated in one place so they're easy to
 * tune.
 *
 * <p>Everything here is plain SI ({@code double}) - meters, seconds, radians - so the math in the
 * trajectory engine and {@code applyTractionFilter} stays unit-free and readable.
 */
public final class Constants {
  private Constants() {} // utility class - never instantiated

  /**
   * Traction (anti-slip) parameters used by {@code CommandSwerveDrivetrain.applyTractionFilter}.
   *
   * <p>The friction circle says a wheel can only transmit force to the carpet up to {@code a_max =
   * mu * g}. Ask for more acceleration than that and the tire breaks loose and slips - you lose
   * both grip and odometry accuracy. The limiter caps the <i>requested</i> translational
   * acceleration at this value.
   */
  public static final class Traction {
    private Traction() {}

    /**
     * Coefficient of friction between the drive wheel tread and the carpet (dimensionless).
     *
     * <p>This is the single most important number for the traction limiter. Typical FRC values:
     * ~0.9-1.1 for blue nitrile / "black" tread on FRC carpet, lower for worn or hard compounds.
     * Measure it for your real wheels; start conservative (lower mu = earlier limiting = safer).
     */
    public static final double kWheelCoF = 0.9;

    /** Gravitational acceleration (m/s^2). Sets the scale of the friction circle via a = mu * g. */
    public static final double kGravity = 9.81;

    /**
     * Robot main-loop period (seconds). The traction filter turns a velocity <i>step</i> into an
     * acceleration by dividing by this dt, so it must match the period the command actually runs at
     * (the WPILib default is 20 ms).
     */
    public static final double kLoopPeriod = 0.020;

    /**
     * The maximum translational acceleration the carpet can support, {@code a_max = mu * g}
     * (m/s^2). Precomputed here so the hot path in the filter is a single comparison.
     */
    public static final double kMaxTranslationAccel = kWheelCoF * kGravity;
  }

  /**
   * Default motion constraints for the custom trajectory engine's decoupled per-axis profiles.
   *
   * <p>These are <i>profile</i> limits (how aggressively we plan a path), separate from the
   * <i>physical</i> traction limit above (which is the hard safety backstop). Keep the planned
   * acceleration at or below {@link Traction#kMaxTranslationAccel} so the limiter rarely has to
   * intervene; the limiter then only catches disturbances (bumps, defense) the plan didn't expect.
   */
  public static final class Trajectory {
    private Trajectory() {}

    /** Max planned translational speed (m/s). Should be <= TunerConstants.kSpeedAt12Volts. */
    public static final double kMaxLinearVelocity = 4.0;

    /** Max planned translational acceleration (m/s^2). Keep <= the traction limit. */
    public static final double kMaxLinearAccel = 8.0;

    /** Max planned angular speed (rad/s). */
    public static final double kMaxAngularVelocity = Math.PI;

    /** Max planned angular acceleration (rad/s^2). */
    public static final double kMaxAngularAccel = 2.0 * Math.PI;

    /**
     * Position error (meters) beyond which the engine assumes a major disturbance (a hard hit or
     * being shoved off-line) and performs a State Reset - it re-anchors the trajectory to the
     * robot's current drifted pose and measured velocity and regenerates from there.
     */
    public static final double kStateResetThreshold = 0.35;

    // --- Position-trim feedback (the X/Y loop that closes out integration drift) ----------------
    //
    // The trajectory engine emits a VELOCITY feedforward - it tells the wheels how fast to move,
    // not
    // where to be. Open-loop, tiny velocity-tracking errors integrate into a steady-state position
    // offset (the 13 cm we saw). These gains drive a per-axis PID on the error between the PLANNED
    // pose at time t and the MEASURED pose, and that correction is ADDED to the feedforward. kP is
    // in (m/s) of correction per meter of error.

    /** Proportional gain for the field X/Y position-trim controllers. TODO: tune. */
    public static final double kTranslationP = 4.0;

    /** Derivative gain for the position-trim controllers (damps the approach). TODO: tune. */
    public static final double kTranslationD = 0.0;

    /**
     * Heading controller gains for CTRE's {@code FieldCentricFacingAngle}. This PID runs on the
     * drivetrain's onboard heading controller (not the module slot gains); output is rad/s of yaw
     * rate per radian of heading error. Raised from the placeholder 5.0 so the robot snaps to the
     * goal facing instead of settling short; a little kD damps overshoot. TODO: tune.
     */
    public static final double kHeadingP = 8.0;

    public static final double kHeadingD = 0.3;

    // --- "At goal" termination (so a leg only ends when the robot is physically there) ----------

    /** Translation tolerance (meters) the robot must be within to call a trajectory finished. */
    public static final double kPositionTolerance = 0.02; // 2 cm

    /** Heading tolerance (radians) the robot must be within to call a trajectory finished. */
    public static final double kHeadingTolerance = Math.toRadians(1.0); // 1 degree

    /**
     * Extra time (seconds) the follower is allowed to keep trimming after the profile's nominal
     * duration before it gives up and reports finished anyway. Prevents a leg from hanging forever
     * if the tolerance can't be met (e.g. pinned by defense); without it, {@code isFinished} could
     * never return true.
     */
    public static final double kSettleTimeout = 1.0;

    // --- Position-based Choreo playback (robust at high speed) --------------------------------

    /**
     * Minimum lookahead distance (meters) for position-based Choreo tracking. Small values hug the
     * path tightly; too small can make the command twitchy when odometry is noisy.
     */
    public static final double kPlaybackLookaheadMin = 0.08;

    /**
     * Maximum lookahead distance (meters). Higher values smooth high-speed tracking but can cut
     * corners if set excessively large.
     */
    public static final double kPlaybackLookaheadMax = 0.35;

    /**
     * Speed-to-lookahead gain (seconds): lookahead = min + gain * speed. This makes lookahead grow
     * with robot speed so fast segments stay stable while slow segments remain precise.
     */
    public static final double kPlaybackLookaheadSpeedGain = 0.04;

    /**
     * How many samples ahead of the previous nearest-point index to search each loop when locking
     * to the path. Limiting search to a forward window keeps runtime cheap and enforces monotonic
     * progress through the path.
     */
    public static final int kPlaybackNearestSearchWindow = 25;
  }

  /**
   * Vision fusion settings used by the Limelight-based pose estimator pipeline.
   *
   * <p>These tune two parts of the estimator behavior:
   *
   * <ol>
   *   <li>Hard gates: reject obviously bad measurements (stale, too far, huge ambiguity, etc.)
   *   <li>Soft trust shaping: accepted measurements get larger/smaller std-devs based on quality
   * </ol>
   */
  public static final class Vision {
    private Vision() {}

    /** Base XY trust coefficient in the distance/tag-count model. */
    public static final double kXYStdDevCoefficient = 0.333;

    /** Base heading trust coefficient for MegaTag1 (2+ tags). */
    public static final double kHeadingStdDevCoefficient = 1.5;

    /** Effectively disables vision heading (used for MegaTag2/single-tag). */
    public static final double kIgnoreVisionHeadingStdDev = 9_999_999;

    /** Reject vision if average tag distance exceeds this (meters). */
    public static final double kMaxTagDistanceMeters = 4.0;

    /** Reject vision if reported latency exceeds this (milliseconds). */
    public static final double kMaxLatencyMs = 120.0;

    /** Reject vision if measurement age now - timestamp exceeds this (seconds). */
    public static final double kMaxMeasurementAgeSec = 0.20;

    /** Reject single-tag updates if fiducial ambiguity exceeds this. */
    public static final double kMaxSingleTagAmbiguity = 0.20;

    /** Reject updates with too little observed tag area (camera far away / noisy). */
    public static final double kMinAvgTagArea = 0.05;

    /** Outlier gate for multi-tag measurements vs current odometry pose (meters). */
    public static final double kMaxPoseJumpMetersMultiTag = 2.5;

    /** Outlier gate for single-tag measurements vs current odometry pose (meters). */
    public static final double kMaxPoseJumpMetersSingleTag = 1.2;

    /** Speed inflation gain for XY std-dev: std *= (1 + gain * speed[m/s]). */
    public static final double kVelocityStdDevInflationGain = 0.12;

    /** Ambiguity inflation gain: std *= (1 + gain * ambiguity). */
    public static final double kAmbiguityStdDevInflationGain = 1.5;

    /**
     * Low-area inflation gain. As avg tag area drops below 1.0, trust is reduced by this factor.
     */
    public static final double kLowAreaStdDevInflationGain = 1.25;

    /** Pose-correction inflation gain: std *= (1 + gain * odom-vs-vision error[m]). */
    public static final double kCorrectionStdDevInflationGain = 0.25;

    /**
     * Reject vision while the chassis is yawing faster than this (rad/s). During a fast spin the
     * camera-to-robot time sync is unreliable and a stale frame lands at a very different heading,
     * so a single-tag solve can be wildly wrong. Team 254 gates on this; we use the current yaw
     * rate as a simple, effective proxy for "was I spinning when this frame was captured".
     */
    public static final double kMaxAngularSpeedForVision = 4.0;

    /**
     * Reject any vision pose whose translation is within this many meters of the field origin (0,
     * 0). A near-origin solve is the classic signature of a bad/empty read, not a real measurement.
     * (254's {@code kDefaultNormThreshold}.)
     */
    public static final double kMinPoseNormMeters = 0.10;

    /**
     * Field size used only for the off-field reject gate below. TODO: set to the real 2026 game
     * field dimensions once known (these are the 2025 Reefscape field as a placeholder). See the
     * {@code game-info} skill.
     */
    public static final double kFieldLengthMeters = 17.55;

    /** Field width for the off-field reject gate. TODO: set to the real 2026 field. */
    public static final double kFieldWidthMeters = 8.05;

    /**
     * Reject any vision pose that lands more than this far outside the field rectangle. A real
     * measurement is always on the field (plus a small margin for the robot's own footprint);
     * anything well outside is an outlier that would yank the estimate off the field.
     */
    public static final double kFieldBoundaryMarginMeters = 0.5;

    /**
     * Distance (m) where crop starts "wide" (almost full frame). Closer than this keeps a large
     * view so tag reacquisition is easy.
     */
    public static final double kCropNearDistanceMeters = 1.5;

    /**
     * Distance (m) where crop reaches its tightest size. Farther than this stays at the same tight
     * crop to maximize FPS / lower latency.
     */
    public static final double kCropFarDistanceMeters = 5.0;

    /**
     * Crop half-size near the target in normalized Limelight crop space [-1, 1]. Bigger = less
     * crop, safer reacquisition, lower max FPS benefit.
     */
    public static final double kCropWindowHalfSizeNear = 0.95;

    /**
     * Crop half-size far from the target. Smaller = tighter crop, better FPS/latency, but easier to
     * lose the target if centering is imperfect.
     */
    public static final double kCropWindowHalfSizeFar = 0.32;

    /** Minimum absolute change required before pushing a new crop window over NT. */
    public static final double kCropApplyDeadband = 0.02;
  }

  /**
   * Tuning for the {@link frc.robot.subsystems.RobotState} pose estimator - the team-owned fusion
   * layer that blends wheel/gyro odometry with vision using a time-interpolated buffer and a
   * steady-state Kalman gain (the same rewind/fuse/forward idea Teams 6328/254/2910 use). These
   * values describe how much to <i>trust odometry</i> between vision corrections; vision trust
   * comes from {@link Vision} (per-measurement std-devs).
   */
  public static final class Estimator {
    private Estimator() {}

    /**
     * How much odometry history to keep for latency compensation (seconds). Must comfortably exceed
     * the worst-case vision latency so a delayed measurement can still be replayed against where
     * the robot actually was when the frame was captured.
     */
    public static final double kPoseBufferSizeSeconds = 2.0;

    /**
     * Odometry translational trust as a standard deviation (meters of drift accumulated per fusion
     * step). Smaller => the estimate leans harder on wheels/gyro and vision nudges it more gently.
     */
    public static final double kOdometryStdDevMeters = 0.003;

    /**
     * Odometry heading trust as a standard deviation (radians). The gyro is very good, so this is
     * small; increase it if you want vision (MegaTag1) to pull heading harder.
     */
    public static final double kOdometryStdDevRadians = 0.002;

    /**
     * Multiply odometry variance by this while collision/skid-like disturbance is active, so vision
     * corrections pull harder.
     */
    public static final double kOdometryVarianceScaleWhenDisturbed = 4.0;

    /** Translational acceleration spike threshold for collision-like events (m/s^2). */
    public static final double kCollisionAccelThresholdMps2 = 7.0;

    /** Speed floor before we evaluate skid-like heuristics (m/s). */
    public static final double kSkidSpeedThresholdMps = 1.6;

    /** Yaw-rate floor before we evaluate skid-like heuristics (rad/s). */
    public static final double kSkidYawRateThresholdRadPerSec = 2.8;

    /** Lateral acceleration threshold for skid-like events while turning (m/s^2). */
    public static final double kSkidLateralAccelThresholdMps2 = 4.0;

    /** Keep odometry de-weighted for this long after a disturbance (s). */
    public static final double kDisturbanceHoldSeconds = 0.30;
  }

  /**
   * Limelight-based gamepiece detection and intake-drive assist tuning.
   *
   * <p>This follows the same high-level idea many top teams use: estimate gamepiece position from
   * camera angles, keep a short "last seen" memory, and assist only while intaking so normal teleop
   * feel stays driver-first.
   */
  public static final class Gamepiece {
    private Gamepiece() {}

    /** Limelight name used for gamepiece detection (must match camera NT name). */
    public static final String kDetectionCamera = "limelight-br";

    /** Neural detector class id to track; set to -1 to accept any detected class. */
    public static final int kDetectionClassId = -1;

    /** Ignore tiny detections below this area (% of image). */
    public static final double kMinDetectionArea = 0.10;

    /**
     * Camera mount pitch (degrees). Positive means the camera points downward toward the carpet.
     * TODO: replace with your measured mount pitch.
     */
    public static final double kCameraPitchDegrees = 24.0;

    /** Camera mount yaw (degrees), positive to robot-left. TODO: replace with measured value. */
    public static final double kCameraYawDegrees = 0.0;

    /** Camera height above carpet (meters). TODO: replace with measured value. */
    public static final double kCameraHeightMeters = 0.56;

    /** Forward offset from robot center to camera (meters). TODO: replace with measured value. */
    public static final double kCameraForwardMeters = 0.30;

    /** Left offset from robot center to camera (meters). TODO: replace with measured value. */
    public static final double kCameraLeftMeters = 0.00;

    /** Expected gamepiece center height above carpet (meters). */
    public static final double kGamepieceHeightMeters = 0.02;

    /** Drop a remembered gamepiece if unseen longer than this (seconds). */
    public static final double kTargetMemorySeconds = 0.35;

    /** Ignore assist when already this close to the piece (meters). */
    public static final double kStopDistanceMeters = 0.22;

    /** Position gain for assist velocity (1/s). */
    public static final double kPursuitGain = 1.8;

    /** Velocity damping gain to avoid overshoot/skid while converging. */
    public static final double kVelocityDamping = 0.65;

    /** Max translational assist speed added by the algorithm (m/s). */
    public static final double kMaxAssistSpeedMetersPerSecond = 1.8;

    /** How strongly assist blends into manual translation while intaking (0-1). */
    public static final double kAssistBlend = 0.70;

    /** Translation slew-rate limit for smooth, non-skidding stick-to-assist transitions (m/s^2). */
    public static final double kTranslationSlewRate = 6.0;

    /** Rotation slew-rate limit for smooth heading changes (rad/s^2). */
    public static final double kRotationSlewRate = 8.0;
  }
}
