// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

/**
 * Central tuning constants for whole-robot behaviors that don't belong to a single generated file.
 *
 * <p>Hardware/drivetrain constants (device IDs, gear ratios, drive PID, {@code kSpeedAt12Volts})
 * are generated by Tuner X and live in {@link frc.robot.generated.TunerConstants} - do not
 * duplicate them here. This class holds the <i>physics</i> and <i>profiling</i> parameters that the
 * custom trajectory engine and the traction limiter need, isolated in one place so they're easy to
 * tune.
 *
 * <p>Everything here is plain SI ({@code double}) - meters, seconds, radians - so the math in the
 * trajectory engine and {@code applyTractionFilter} stays unit-free and readable.
 */
public final class Constants {
  private Constants() {} // utility class - never instantiated

  /**
   * Traction (anti-slip) parameters used by {@code CommandSwerveDrivetrain.applyTractionFilter}.
   *
   * <p>The friction circle says a wheel can only transmit force to the carpet up to {@code a_max =
   * mu * g}. Ask for more acceleration than that and the tire breaks loose and slips - you lose
   * both grip and odometry accuracy. The limiter caps the <i>requested</i> translational
   * acceleration at this value.
   */
  public static final class Traction {
    private Traction() {}

    /**
     * Coefficient of friction between the drive wheel tread and the carpet (dimensionless).
     *
     * <p>This is the single most important number for the traction limiter. Typical FRC values:
     * ~0.9-1.1 for blue nitrile / "black" tread on FRC carpet, lower for worn or hard compounds.
     * Measure it for your real wheels; start conservative (lower mu = earlier limiting = safer).
     */
    public static final double kWheelCoF = 0.9;

    /** Gravitational acceleration (m/s^2). Sets the scale of the friction circle via a = mu * g. */
    public static final double kGravity = 9.81;

    /**
     * Robot main-loop period (seconds). The traction filter turns a velocity <i>step</i> into an
     * acceleration by dividing by this dt, so it must match the period the command actually runs at
     * (the WPILib default is 20 ms).
     */
    public static final double kLoopPeriod = 0.020;

    /**
     * The maximum translational acceleration the carpet can support, {@code a_max = mu * g}
     * (m/s^2). Precomputed here so the hot path in the filter is a single comparison.
     */
    public static final double kMaxTranslationAccel = kWheelCoF * kGravity;
  }

  /**
   * Default motion constraints for the custom trajectory engine's decoupled per-axis profiles.
   *
   * <p>These are <i>profile</i> limits (how aggressively we plan a path), separate from the
   * <i>physical</i> traction limit above (which is the hard safety backstop). Keep the planned
   * acceleration at or below {@link Traction#kMaxTranslationAccel} so the limiter rarely has to
   * intervene; the limiter then only catches disturbances (bumps, defense) the plan didn't expect.
   */
  public static final class Trajectory {
    private Trajectory() {}

    /** Max planned translational speed (m/s). Should be <= TunerConstants.kSpeedAt12Volts. */
    public static final double kMaxLinearVelocity = 4.0;

    /** Max planned translational acceleration (m/s^2). Keep <= the traction limit. */
    public static final double kMaxLinearAccel = 8.0;

    /** Max planned angular speed (rad/s). */
    public static final double kMaxAngularVelocity = Math.PI;

    /** Max planned angular acceleration (rad/s^2). */
    public static final double kMaxAngularAccel = 2.0 * Math.PI;

    /**
     * Position error (meters) beyond which the engine assumes a major disturbance (a hard hit or
     * being shoved off-line) and performs a State Reset - it re-anchors the trajectory to the
     * robot's current drifted pose and measured velocity and regenerates from there.
     */
    public static final double kStateResetThreshold = 0.35;

    // --- Position-trim feedback (the X/Y loop that closes out integration drift) ----------------
    //
    // The trajectory engine emits a VELOCITY feedforward - it tells the wheels how fast to move,
    // not
    // where to be. Open-loop, tiny velocity-tracking errors integrate into a steady-state position
    // offset (the 13 cm we saw). These gains drive a per-axis PID on the error between the PLANNED
    // pose at time t and the MEASURED pose, and that correction is ADDED to the feedforward. kP is
    // in (m/s) of correction per meter of error.

    /** Proportional gain for the field X/Y position-trim controllers. TODO: tune. */
    public static final double kTranslationP = 4.0;

    /** Derivative gain for the position-trim controllers (damps the approach). TODO: tune. */
    public static final double kTranslationD = 0.0;

    /**
     * Heading controller gains for CTRE's {@code FieldCentricFacingAngle}. This PID runs on the
     * drivetrain's onboard heading controller (not the module slot gains); output is rad/s of yaw
     * rate per radian of heading error. Raised from the placeholder 5.0 so the robot snaps to the
     * goal facing instead of settling short; a little kD damps overshoot. TODO: tune.
     */
    public static final double kHeadingP = 8.0;

    public static final double kHeadingD = 0.3;

    // --- "At goal" termination (so a leg only ends when the robot is physically there) ----------

    /** Translation tolerance (meters) the robot must be within to call a trajectory finished. */
    public static final double kPositionTolerance = 0.02; // 2 cm

    /** Heading tolerance (radians) the robot must be within to call a trajectory finished. */
    public static final double kHeadingTolerance = Math.toRadians(1.0); // 1 degree

    /**
     * Extra time (seconds) the follower is allowed to keep trimming after the profile's nominal
     * duration before it gives up and reports finished anyway. Prevents a leg from hanging forever
     * if the tolerance can't be met (e.g. pinned by defense); without it, {@code isFinished} could
     * never return true.
     */
    public static final double kSettleTimeout = 1.0;
  }
}
