package frc.robot.subsystems;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import org.wpilib.driverstation.Alliance;
import org.wpilib.driverstation.MatchState;
import org.wpilib.driverstation.RobotState;
import org.wpilib.math.geometry.Rotation2d;
import org.wpilib.math.kinematics.ChassisVelocities;
import org.wpilib.system.Notifier;
import org.wpilib.system.RobotController;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class. It owns the hardware and odometry; the
 * command-based wrapping (requirements, default command, request commands) lives in {@link
 * DriveMechanism}, because Commands v3 {@code Mechanism} is a class and this already extends the
 * Tuner-generated drivetrain.
 *
 * <p>Generated by the 2027 Tuner X Swerve Project Generator; together with {@code TunerConstants}
 * it is an example placeholder - regenerate both for your robot from Tuner X.
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain {
  private static final double SIM_LOOP_PERIOD = 0.004; // 4 ms
  private Notifier simNotifier = null;
  private double lastSimTime;

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean hasAppliedOperatorPerspective = false;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
  }

  /**
   * Keeps the operator drive perspective aligned with the alliance color. Driven periodically by
   * {@link DriveMechanism} (registered on the scheduler), since this class is no longer itself a
   * command-based subsystem with a {@code periodic()} hook.
   */
  public void applyOperatorPerspective() {
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is disabled.
     * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
     */
    if (!hasAppliedOperatorPerspective || RobotState.isDisabled()) {
      MatchState.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.RED
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                hasAppliedOperatorPerspective = true;
              });
    }
  }

  /**
   * Proportional traction (anti-slip) limiter for a requested field-relative velocity command.
   *
   * <p><b>The physics.</b> A drive wheel can only push on the carpet up to the friction limit. The
   * most acceleration the robot can produce without the tires breaking loose is the friction circle
   * radius:
   *
   * <pre>a_max = mu * g</pre>
   *
   * where {@code mu} is the wheel-on-carpet coefficient of friction ({@link
   * Constants.Traction#kWheelCoF}) and {@code g} is gravity. Command more than that during a
   * violent direction change or a defensive hit and the wheels slip - you lose grip, control, and
   * odometry.
   *
   * <p><b>What this does.</b> Treat the difference between where we're going ({@code targetSpeeds})
   * and where we are ({@code getState().Velocity}) as a velocity step that must happen in one loop
   * ({@code dt = 20 ms}). That step implies a translational acceleration vector {@code a =
   * (dv/dt)}. If its magnitude {@code sqrt(ax^2 + ay^2)} exceeds {@code a_max}, we scale the
   * acceleration vector back to the edge of the friction circle - keeping its DIRECTION - and apply
   * only that much change this loop. The result rides the traction limit instead of blowing past
   * it.
   *
   * <p><b>Heading is preserved.</b> Only the translational components {@code vx, vy} are scaled;
   * the requested rotational rate {@code omega} passes through untouched, so the limiter never
   * sacrifices heading authority to save translation grip.
   *
   * <p>The {@code targetSpeeds} must be <b>field-relative</b> (the same frame a field-centric
   * request consumes). The measured velocity from the state is robot-relative, so we rotate it into
   * the field frame first to compute the step in a consistent frame.
   *
   * @param targetSpeeds the desired field-relative chassis velocity ({@code vx, vy} m/s, {@code
   *     omega} rad/s)
   * @return a field-relative velocity that respects the friction circle, with {@code omega}
   *     unchanged
   */
  public ChassisVelocities applyTractionFilter(ChassisVelocities targetSpeeds) {
    final double dt = Constants.Traction.kLoopPeriod;
    final double aMax = Constants.Traction.kMaxTranslationAccel; // = mu * g

    // Measured velocity is robot-relative in the state; rotate it into the field frame so the
    // requested-minus-actual subtraction below happens in one consistent (field) frame.
    ChassisVelocities current = getState().Velocity.toFieldRelative(getState().Pose.getRotation());

    // Required translational acceleration to reach the target in one loop: a = (v_target -
    // v_now)/dt.
    double ax = (targetSpeeds.vx - current.vx) / dt;
    double ay = (targetSpeeds.vy - current.vy) / dt;
    double aMag = Math.hypot(ax, ay);

    // Inside the friction circle (or no change requested): the command is already achievable.
    if (aMag <= aMax || aMag == 0.0) {
      return targetSpeeds;
    }

    // Outside the circle: keep the acceleration DIRECTION, shrink its MAGNITUDE to exactly a_max.
    // scale < 1, so we only apply (scale) of the requested velocity step this loop - the velocity
    // that actually lands on the friction-circle boundary.
    double scale = aMax / aMag;
    double vx = current.vx + (targetSpeeds.vx - current.vx) * scale;
    double vy = current.vy + (targetSpeeds.vy - current.vy) * scale;

    // omega is intentionally untouched - heading control is never traded away for translation grip.
    return new ChassisVelocities(vx, vy, targetSpeeds.omega);
  }

  private void startSimThread() {
    lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - lastSimTime;
              lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    simNotifier.startPeriodic(SIM_LOOP_PERIOD);
  }
}
