// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveRequest;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants;
import frc.robot.utils.Telemetry;
import java.util.function.Supplier;
import org.wpilib.command3.Command;
import org.wpilib.command3.Mechanism;
import org.wpilib.command3.Scheduler;
import org.wpilib.math.geometry.Pose2d;
import org.wpilib.math.kinematics.ChassisVelocities;
import org.wpilib.math.linalg.Matrix;
import org.wpilib.math.numbers.N1;
import org.wpilib.math.numbers.N3;
import org.wpilib.networktables.DoublePublisher;
import org.wpilib.networktables.NetworkTable;
import org.wpilib.networktables.NetworkTableInstance;

/**
 * Command-based wrapper around {@link CommandSwerveDrivetrain}. The drivetrain already extends the
 * Tuner-generated class, so it can't also be a {@code Mechanism} (which is a class in Commands v3);
 * this owns the drivetrain instead and exposes the drive commands.
 */
public class DriveMechanism extends Mechanism {
  // CTRE-recommended construction: TunerConstants is generated by Tuner X and createDrivetrain()
  // is its factory. Keep this verbatim and regenerate TunerConstants from Tuner X for your robot
  // (the checked-in one is an EXAMPLE placeholder with fake device IDs/gains).
  private final CommandSwerveDrivetrain drivetrain = TunerConstants.createDrivetrain();

  // Publishes the drivetrain state to NetworkTables (and thus the WPILOG via DataLogManager). This
  // is the project's logging surface - see Telemetry and the log-reading skill.
  private final Telemetry telemetry = new Telemetry();

  // Team-owned pose estimator that fuses this drivetrain's odometry with vision (see RobotState).
  // We keep the Phoenix estimator odometry-only and do the vision fusion here so it is fully
  // visible in the log and tunable - the way 6328/254/2910 structure their code.
  private final RobotState robotState = new RobotState();

  // Disturbance detection (collision/skid-like heuristics) used to de-weight odometry temporarily,
  // matching the "trust tags more when disturbed" strategy top teams use.
  private ChassisVelocities lastFieldVelocity = new ChassisVelocities();
  private double lastVelocityTimestamp = Double.NaN;
  private double disturbanceUntilTimestamp = Double.NEGATIVE_INFINITY;

  private final NetworkTable estimatorTable =
      NetworkTableInstance.getDefault().getTable("RobotState").getSubTable("Disturbance");
  private final DoublePublisher accelMps2Pub = estimatorTable.getDoubleTopic("AccelMps2").publish();
  private final DoublePublisher lateralAccelMps2Pub =
      estimatorTable.getDoubleTopic("LateralAccelMps2").publish();
  private final DoublePublisher disturbedPub = estimatorTable.getDoubleTopic("Disturbed").publish();

  public DriveMechanism() {
    super("Drivetrain");
    // The drivetrain's perspective update used to live in periodic(); run it every loop.
    Scheduler.getDefault().addPeriodic(drivetrain::applyOperatorPerspective);
    // Feed odometry into RobotState every loop, before vision runs (this periodic is registered
    // before any Limelight periodic, so the odometry buffer is fresh when vision fuses).
    Scheduler.getDefault().addPeriodic(this::updateRobotState);
    // CTRE calls this from the odometry thread every time a new state is produced (250 Hz on FD).
    drivetrain.registerTelemetry(telemetry::telemeterize);
  }

  /** Pushes the latest Phoenix odometry snapshot into the team pose estimator. */
  private void updateRobotState() {
    var state = drivetrain.getState();
    ChassisVelocities fieldVelocity = state.Velocity.toFieldRelative(state.Pose.getRotation());

    evaluateOdometryDisturbance(fieldVelocity, state.Timestamp);
    boolean disturbedNow = Utils.getCurrentTimeSeconds() <= disturbanceUntilTimestamp;
    robotState.setOdometryVarianceScale(
        disturbedNow ? Constants.Estimator.kOdometryVarianceScaleWhenDisturbed : 1.0);
    disturbedPub.set(disturbedNow ? 1.0 : 0.0);

    robotState.addOdometryObservation(state.Pose, fieldVelocity, state.Timestamp);
  }

  private void evaluateOdometryDisturbance(
      ChassisVelocities currentFieldVelocity, double timestamp) {
    if (!Double.isFinite(lastVelocityTimestamp)) {
      lastFieldVelocity = currentFieldVelocity;
      lastVelocityTimestamp = timestamp;
      accelMps2Pub.set(0.0);
      lateralAccelMps2Pub.set(0.0);
      return;
    }

    double dt = Math.max(1e-3, timestamp - lastVelocityTimestamp);
    double ax = (currentFieldVelocity.vx - lastFieldVelocity.vx) / dt;
    double ay = (currentFieldVelocity.vy - lastFieldVelocity.vy) / dt;
    double accelMag = Math.hypot(ax, ay);
    double speed = Math.hypot(currentFieldVelocity.vx, currentFieldVelocity.vy);
    double lateralAccelMag =
        speed > 1e-3
            ? Math.abs((-currentFieldVelocity.vy * ax + currentFieldVelocity.vx * ay) / speed)
            : 0.0;

    accelMps2Pub.set(accelMag);
    lateralAccelMps2Pub.set(lateralAccelMag);

    boolean collisionLike = accelMag >= Constants.Estimator.kCollisionAccelThresholdMps2;
    boolean skidLike =
        speed >= Constants.Estimator.kSkidSpeedThresholdMps
            && Math.abs(currentFieldVelocity.omega)
                >= Constants.Estimator.kSkidYawRateThresholdRadPerSec
            && lateralAccelMag >= Constants.Estimator.kSkidLateralAccelThresholdMps2;

    if (collisionLike || skidLike) {
      disturbanceUntilTimestamp =
          Math.max(
              disturbanceUntilTimestamp,
              Utils.getCurrentTimeSeconds() + Constants.Estimator.kDisturbanceHoldSeconds);
    }

    lastFieldVelocity = currentFieldVelocity;
    lastVelocityTimestamp = timestamp;
  }

  /** Returns a command that continuously applies the supplied control request to the drivetrain. */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return runRepeatedly(() -> drivetrain.setControl(request.get())).named("applyRequest");
  }

  /** Resets the field-centric heading so "forward" matches the driver's current facing. */
  public Command seedFieldCentric() {
    return run(coroutine -> {
          drivetrain.seedFieldCentric();
        })
        .named("seedFieldCentric");
  }

  /**
   * Applies a swerve control request to the underlying drivetrain. Exposed so a command that
   * already requires this mechanism (e.g. {@code DriveToTag}) can drive it without needing direct
   * access to the Phoenix swerve object.
   */
  public void setControl(SwerveRequest request) {
    drivetrain.setControl(request);
  }

  /**
   * The robot's current fused field pose (odometry + vision), in the blue-alliance-origin field
   * frame (the Phoenix convention - the origin does not flip with alliance). Used by pose-following
   * commands such as {@code DriveToPose} for feedback. See {@link RobotState}.
   */
  public Pose2d getPose() {
    return robotState.getEstimatedPose();
  }

  /**
   * The robot's odometry-only field pose (no vision). Feed this to single-tag vision (MegaTag2),
   * which needs a heading input that does not itself depend on vision, to avoid a feedback loop.
   */
  public Pose2d getOdometryPose() {
    return robotState.getOdometryPose();
  }

  /**
   * Teleports the odometry estimate to {@code pose} (blue-alliance-origin field frame). This does
   * not move the robot - it redefines where odometry thinks the robot currently is. Autonomous
   * routines call this at the start so the robot's believed pose matches the trajectory's first
   * point; without it a path that starts far from the robot's current pose would look like a huge
   * position error and the follower would try to "correct" straight to the goal.
   */
  public void resetPose(Pose2d pose) {
    // Reset the Phoenix odometry baseline AND the fused estimate so both agree on the new origin.
    drivetrain.resetPose(pose);
    robotState.resetPose(pose);
  }

  /**
   * The robot's current field-relative velocity from odometry. The drivetrain reports a
   * robot-centric velocity; this rotates it into the field frame so it can seed a field-relative
   * profile (e.g. {@code LinearPath}).
   */
  public ChassisVelocities getFieldVelocity() {
    var state = drivetrain.getState();
    return state.Velocity.toFieldRelative(state.Pose.getRotation());
  }

  /**
   * Runs a requested field-relative velocity through the drivetrain's physics-based traction
   * limiter, capping translational acceleration at the friction circle so the wheels don't slip.
   * Exposed so a follow command (e.g. {@code AdvancedTrackTrajectory}) can protect its trajectory
   * feedforward without direct access to the Phoenix swerve object. See {@link
   * CommandSwerveDrivetrain#applyTractionFilter}.
   */
  public ChassisVelocities applyTractionFilter(ChassisVelocities targetSpeeds) {
    return drivetrain.applyTractionFilter(targetSpeeds);
  }

  /**
   * Fuses a vision pose estimate into the team {@link RobotState} estimator. Exposed so the {@link
   * frc.robot.subsystems.vision.Limelight} pose estimator can correct odometry without direct
   * access to the estimator or the Phoenix swerve object.
   *
   * <p><b>Timebase:</b> {@link RobotState} keys its odometry buffer with {@code
   * Utils.getCurrentTimeSeconds()} (the drivetrain state timestamp), so {@code timestampSeconds}
   * must be in that same epoch. Limelight reports timestamps in the WPILib timebase ({@code
   * Timer.getTimestamp()}); the {@code Limelight} subsystem converts before calling this. (Phoenix
   * 6 dropped {@code Utils.fpgaToCurrentTime} in the 2027 line, so the conversion is done by
   * sampling the offset there.)
   *
   * @param visionRobotPose the robot pose measured by vision, blue-alliance-origin
   * @param timestampSeconds measurement timestamp in the {@code Utils.getCurrentTimeSeconds()}
   *     epoch
   * @param stdDevs measurement standard deviations [x, y, theta]ᵀ (meters, radians)
   */
  public void addVisionMeasurement(
      Pose2d visionRobotPose, double timestampSeconds, Matrix<N3, N1> stdDevs) {
    // Fuse in RobotState (not the Phoenix estimator) so the Phoenix pose stays odometry-only and
    // the correction is not double-counted when RobotState reads that pose back as odometry.
    robotState.addVisionObservation(visionRobotPose, timestampSeconds, stdDevs);
  }
}
